# Build and deploy the website to Vercel.
#
# This workflow is run on every commit to the main branch.
#
name: Vercel deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link project
        run: vercel link --project spacetype-web --yes --token ${{ secrets.VERCEL_ACCOUNT_TOKEN }}

      - name: Deploy
        run: |
          vercel --token ${{ secrets.VERCEL_ACCOUNT_TOKEN }} deploy --prod
